
<!-- CAROUSEL section.  Images should be 1290x392 -->
      <div id="carouselIndicators" class="carousel slide" data-ride="carousel" data-interval="7000">
<!-- The little dashes to indicate which slide you are on -->
        <ol class="carousel-indicators">
          <li data-target="#carouselIndicators" data-slide-to="0" class="active"></li>
          <li data-target="#carouselIndicators" data-slide-to="1"></li>
          <li data-target="#carouselIndicators" data-slide-to="2"></li>
          <li data-target="#carouselIndicators" data-slide-to="3"></li>
          <li data-target="#carouselIndicators" data-slide-to="4"></li>
        </ol>
        <div class="carousel-inner" role="listbox">
          <!-- Slide One - Set the background image for this slide in the line below -->
          <div class="carousel-item active img-fluid" >
            <img src="images/ADASS2018_Banner.png" style="max-width: 100%; height:auto; margin-top:15px;">
          </div>
          <!-- Slide Two - Set the background image for this slide in the line below -->
          <div class="carousel-item img-fluid">
            <img src="images/chapel.png" style="max-width:100%; height:auto; margin-top:15px;">
          </div>
          <!-- Slide 3 - Set the background image for this slide in the line below -->
          <div class="carousel-item img-fluid">
            <img src="images/theM.png" style="max-width:100%; height:auto; margin-top:15px;">
          </div>
          <!-- Slide 4 - Set the background image for this slide in the line below -->
          <div class="carousel-item img-fluid">
            <img src="images/Testudo_05172013_8630.png" style="max-width:100%; height:auto; margin-top:15px;">
          </div>
          <!-- Slide 5 - Set the background image for this slide in the line below -->
          <div class="carousel-item img-fluid">
            <img src="images/MainAdmin_10162012_0386.png" style="max-width:100%; height:auto; margin-top:15px;">
          </div>
        </div><!--/.carousel-inner-->

<!-- The little left/right arrows to change slide -->
        <a class="carousel-control-prev" href="#carouselIndicators" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselIndicators" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>
